"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _normalize_samesite(value):
    value = (value or "").strip()
    return {
        "lax": "Lax",
        "strict": "Strict",
        "none": "None",
    }.get(value.lower(), value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    cast=Csv(),
    default="localhost,127.0.0.1,0.0.0.0,pixyish-chae-doziest.ngrok-free.dev",
)


# Application definition

INSTALLED_APPS = [
    "unfold",          # django admin theme
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Custom apps
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "schema_viewer",
    
    # Local apps
    "djapps.user_management.apps.UserManagementConfig",
    "djapps.datasets.apps.DatasetsConfig",
    "djapps.gateway.apps.GatewayConfig"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "config.api.middleware.RequestIDMiddleware",
    "config.api.middleware.FrontendCredentialCorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
        "CONN_MAX_AGE" : 0,
        "OPTIONS":{
            "pool":{
                "min_size":2,
                "max_size":10,
                "timeout":30
            }
            
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "djapps.user_management.password_validators.StrongPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="no-reply@smarthub.local")

DATASET_MAX_UPLOAD_SIZE = config(
    "DATASET_MAX_UPLOAD_SIZE",
    cast=int,
    default=50 * 1024 * 1024,
)
DATASET_ALLOWED_FILE_EXTENSIONS = tuple(
    item.strip().lower()
    for item in config(
        "DATASET_ALLOWED_FILE_EXTENSIONS",
        default=".csv,.json,.pdf,.tsv,.txt,.xls,.xlsx,.xml,.sdmx,.zip",
    ).split(",")
    if item.strip()
)

AUTH_USER_MODEL = "user_management.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "djapps.user_management.api.authentication.VersionedJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": config("DRF_THROTTLE_ANON_RATE", default="100/hour"),
        "user": config("DRF_THROTTLE_USER_RATE", default="1000/day"),
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "config.api.exceptions.standardized_exception_handler",
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=config("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", cast=int, default=15)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=config("JWT_REFRESH_TOKEN_LIFETIME_DAYS", cast=int, default=7)
    ),
    "ROTATE_REFRESH_TOKENS": config(
        "JWT_ROTATE_REFRESH_TOKENS",
        cast=bool,
        default=True,
    ),
    "BLACKLIST_AFTER_ROTATION": config(
        "JWT_BLACKLIST_AFTER_ROTATION",
        cast=bool,
        default=True,
    ),
}

AUTH_ACCESS_COOKIE_NAME = config(
    "AUTH_ACCESS_COOKIE_NAME",
    default="smarthub_access_token",
)
AUTH_ACCESS_COOKIE_SECURE = config(
    "AUTH_ACCESS_COOKIE_SECURE",
    cast=bool,
    default=not DEBUG,
)
AUTH_ACCESS_COOKIE_HTTP_ONLY = True
AUTH_ACCESS_COOKIE_SAMESITE = _normalize_samesite(
    config("AUTH_ACCESS_COOKIE_SAMESITE", default="Lax")
)
AUTH_ACCESS_COOKIE_PATH = config(
    "AUTH_ACCESS_COOKIE_PATH",
    default="/api/v1/",
)
AUTH_ACCESS_COOKIE_DOMAIN = (
    config("AUTH_ACCESS_COOKIE_DOMAIN", default="").strip() or None
)

AUTH_REFRESH_COOKIE_NAME = config(
    "AUTH_REFRESH_COOKIE_NAME",
    default="smarthub_refresh_token",
)
AUTH_REFRESH_COOKIE_SECURE = config(
    "AUTH_REFRESH_COOKIE_SECURE",
    cast=bool,
    default=not DEBUG,
)
AUTH_REFRESH_COOKIE_HTTP_ONLY = True
AUTH_REFRESH_COOKIE_SAMESITE = _normalize_samesite(
    config("AUTH_REFRESH_COOKIE_SAMESITE", default=AUTH_ACCESS_COOKIE_SAMESITE)
)
AUTH_REFRESH_COOKIE_PATH = config(
    "AUTH_REFRESH_COOKIE_PATH",
    default="/api/v1/auth/",
)
AUTH_REFRESH_COOKIE_DOMAIN = (
    config("AUTH_REFRESH_COOKIE_DOMAIN", default="").strip()
    or AUTH_ACCESS_COOKIE_DOMAIN
)

DEFAULT_LOCAL_FRONTEND_ORIGINS = (
    "http://localhost:4200",
    "http://127.0.0.1:4200",
) if DEBUG else ()

CONFIGURED_CORS_ALLOWED_ORIGINS = tuple(
    item.strip()
    for item in config("CORS_ALLOWED_ORIGINS", default="").split(",")
    if item.strip()
)
CORS_ALLOWED_ORIGINS = tuple(
    dict.fromkeys(
        (
            *DEFAULT_LOCAL_FRONTEND_ORIGINS,
            *CONFIGURED_CORS_ALLOWED_ORIGINS,
        )
    )
)
CORS_ALLOW_CREDENTIALS = config(
    "CORS_ALLOW_CREDENTIALS",
    cast=bool,
    default=True,
)
CORS_ALLOW_HEADERS = (
    "Accept",
    "Authorization",
    "Content-Type",
    "X-CSRFToken",
    "X-Request-ID",
)
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)
CORS_EXPOSE_HEADERS = (
    "X-Request-ID",
)
CORS_PREFLIGHT_MAX_AGE = config(
    "CORS_PREFLIGHT_MAX_AGE",
    cast=int,
    default=86400,
)

CONFIGURED_CSRF_TRUSTED_ORIGINS = tuple(
    item.strip()
    for item in config("CSRF_TRUSTED_ORIGINS", default="").split(",")
    if item.strip()
)
CSRF_TRUSTED_ORIGINS = tuple(
    dict.fromkeys(
        (
            *DEFAULT_LOCAL_FRONTEND_ORIGINS,
            *CONFIGURED_CSRF_TRUSTED_ORIGINS,
        )
    )
) or CORS_ALLOWED_ORIGINS
CSRF_COOKIE_NAME = config("CSRF_COOKIE_NAME", default="csrftoken")
CSRF_COOKIE_SECURE = config(
    "CSRF_COOKIE_SECURE",
    cast=bool,
    default=AUTH_REFRESH_COOKIE_SECURE,
)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = _normalize_samesite(
    config("CSRF_COOKIE_SAMESITE", default=AUTH_REFRESH_COOKIE_SAMESITE)
)
CSRF_COOKIE_PATH = config(
    "CSRF_COOKIE_PATH",
    default=AUTH_ACCESS_COOKIE_PATH,
)
CSRF_COOKIE_DOMAIN = (
    config("CSRF_COOKIE_DOMAIN", default="").strip() or AUTH_REFRESH_COOKIE_DOMAIN
)

GITHUB_OAUTH_CLIENT_ID = config("GITHUB_OAUTH_CLIENT_ID", default="")
GITHUB_OAUTH_CLIENT_SECRET = config("GITHUB_OAUTH_CLIENT_SECRET", default="")
GITHUB_OAUTH_ALLOWED_REDIRECT_URIS = tuple(
    item.strip()
    for item in config("GITHUB_OAUTH_ALLOWED_REDIRECT_URIS", default="").split(",")
    if item.strip()
)

CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL",
    default="redis://localhost:6379/0",
)
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default=CELERY_BROKER_URL,
)
CELERY_ACCEPT_CONTENT = ("json",)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = config(
    "CELERY_TASK_TRACK_STARTED",
    cast=bool,
    default=True,
)
CELERY_TASK_ALWAYS_EAGER = config(
    "CELERY_TASK_ALWAYS_EAGER",
    cast=bool,
    default=False,
)
CELERY_TASK_EAGER_PROPAGATES = config(
    "CELERY_TASK_EAGER_PROPAGATES",
    cast=bool,
    default=False,
)
CELERY_TASK_DEFAULT_QUEUE = config(
    "CELERY_TASK_DEFAULT_QUEUE",
    default="default",
)
CELERY_WORKER_PREFETCH_MULTIPLIER = config(
    "CELERY_WORKER_PREFETCH_MULTIPLIER",
    cast=int,
    default=1,
)
CELERY_TASK_TIME_LIMIT = config(
    "CELERY_TASK_TIME_LIMIT",
    cast=int,
    default=1800,
)
CELERY_TASK_SOFT_TIME_LIMIT = config(
    "CELERY_TASK_SOFT_TIME_LIMIT",
    cast=int,
    default=1500,
)
PASSWORD_RESET_TOKEN_MAX_AGE = config(
    "PASSWORD_RESET_TOKEN_MAX_AGE",
    cast=int,
    default=3600,
)
EMAIL_VERIFICATION_TOKEN_MAX_AGE = config(
    "EMAIL_VERIFICATION_TOKEN_MAX_AGE",
    cast=int,
    default=86400,
)
FRONTEND_PASSWORD_RESET_URL = config("FRONTEND_PASSWORD_RESET_URL", default="")
FRONTEND_EMAIL_VERIFICATION_URL = config("FRONTEND_EMAIL_VERIFICATION_URL", default="")

SPECTACULAR_SETTINGS = {
    'TITLE': 'Smarthub Project API',
    'DESCRIPTION': (
        'APIs for SmartHub. '
        'Protected endpoints accept JWT bearer access tokens with the header '
        '`Authorization: Bearer <access_token>` or an HttpOnly access-token cookie. '
        'Access and refresh tokens are issued in HttpOnly cookies. '
        'Successful responses are wrapped as `{success, message, data}` and '
        'errors are wrapped as `{success: false, error: {...}}`.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'PREPROCESSING_HOOKS': [
        'config.api.spectacular.keep_canonical_api_endpoints',
    ],
    'SORT_OPERATIONS': True,
    'SORT_OPERATION_PARAMETERS': True,
    'TAGS': [
        {'name': 'Authentication', 'description': 'JWT and social authentication endpoints.'},
        {'name': 'Authorization', 'description': 'Role and permission protected endpoints.'},
        {'name': 'Datasets', 'description': 'Dataset discovery and core dataset CRUD endpoints.'},
        {'name': 'Dataset Workflow', 'description': 'Review and publication workflow endpoints.'},
        {'name': 'Dataset Taxonomy', 'description': 'Category and tag taxonomy endpoints.'},
        {'name': 'Dataset Files', 'description': 'Dataset file upload, download, and file metadata endpoints.'},
        {'name': 'Dataset Audit', 'description': 'Dataset audit, indexing, and status history endpoints.'},
        {'name': 'Gateway', 'description': 'Public and API-key dataset access endpoints.'},
        {'name': 'Developer API Keys', 'description': 'Developer API key management and usage endpoints.'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'docExpansion': 'list',
    },
    'ENUM_NAME_OVERRIDES': {
        'DatasetWorkflowStatusEnum': 'djapps.datasets.models.DatasetStatus.CHOICES',
        'APIConsumerStatusEnum': 'djapps.gateway.models.APIConsumer.STATUS_CHOICES',
        'APIKeyStatusEnum': 'djapps.gateway.models.APIKey.STATUS_CHOICES',
        'DatasetBulkActionEnum': 'djapps.datasets.serializers.DATASET_ADMIN_BULK_ACTION_CHOICES',
        'DatasetReviewActionEnum': 'djapps.datasets.serializers.DATASET_REVIEW_ACTION_CHOICES',
        'DatasetFileValidationStatusEnum': 'djapps.datasets.models.FileValidationStatus.CHOICES',
        'DatasetFrequencyEnum': 'djapps.datasets.models.DatasetFrequency.CHOICES',
        'APIConsumerTypeEnum': 'djapps.gateway.models.APIConsumer.CONSUMER_TYPES',
    },
}


UNFOLD = {
    "SITE_TITLE": "smarthub",
    "SITE_HEADER": "SMARTHUB ADMIN PANEL",
    "SITE_SUBHEADER": "Admin panel for Smarthub",
}
