"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    cast=Csv(),
    default="localhost,127.0.0.1,0.0.0.0,pixyish-chae-doziest.ngrok-free.dev",
)


# Application definition

INSTALLED_APPS = [
    "unfold",          # django admin theme
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Custom apps
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "schema_viewer",
    
    # Local apps
    "djapps.user_management.apps.UserManagementConfig",
    "djapps.datasets.apps.DatasetsConfig",
    "djapps.gateway.apps.GatewayConfig"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "config.api.middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
        "CONN_MAX_AGE" : 0,
        "OPTIONS":{
            "pool":{
                "min_size":2,
                "max_size":10,
                "timeout":30
            }
            
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DATASET_MAX_UPLOAD_SIZE = config(
    "DATASET_MAX_UPLOAD_SIZE",
    cast=int,
    default=50 * 1024 * 1024,
)
DATASET_ALLOWED_FILE_EXTENSIONS = tuple(
    item.strip().lower()
    for item in config(
        "DATASET_ALLOWED_FILE_EXTENSIONS",
        default=".csv,.json,.pdf,.tsv,.txt,.xls,.xlsx,.xml,.sdmx,.zip",
    ).split(",")
    if item.strip()
)

AUTH_USER_MODEL = "user_management.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "EXCEPTION_HANDLER": "config.api.exceptions.standardized_exception_handler",
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Smarthub Project API',
    'DESCRIPTION': (
        'APIs for SmartHub. '
        'Protected endpoints use JWT bearer authentication with the header '
        '`Authorization: Bearer <access_token>`. '
        'Successful responses are wrapped as `{success, message, data}` and '
        'errors are wrapped as `{success: false, error: {...}}`.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': True,
    'SORT_OPERATION_PARAMETERS': True,
    'TAGS': [
        {'name': 'Authentication', 'description': 'JWT and social authentication endpoints.'},
        {'name': 'Authorization', 'description': 'Role and permission protected endpoints.'},
        {'name': 'Datasets', 'description': 'Dataset discovery and core dataset CRUD endpoints.'},
        {'name': 'Dataset Workflow', 'description': 'Review and publication workflow endpoints.'},
        {'name': 'Dataset Taxonomy', 'description': 'Category and tag taxonomy endpoints.'},
        {'name': 'Dataset Files', 'description': 'Dataset file upload, download, and file metadata endpoints.'},
        {'name': 'Dataset Audit', 'description': 'Dataset audit, indexing, and status history endpoints.'},
        {'name': 'Gateway', 'description': 'Public and API-key dataset access endpoints.'},
        {'name': 'Developer API Keys', 'description': 'Developer API key management and usage endpoints.'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'docExpansion': 'list',
    },
}


UNFOLD = {
    "SITE_TITLE": "smarthub",
    "SITE_HEADER": "SMARTHUB ADMIN PANEL",
    "SITE_SUBHEADER": "Admin panel for Smarthub",
}