# Generated by Django 6.0.5 on 2026-06-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0002_apiusagelog_created_at_and_dataset_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusagelog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
