# Generated by Django 6.0.5 on 2026-07-06 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0003_alter_apiusagelog_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apiconsumer",
            index=models.Index(
                fields=["status", "-created_at"], name="api_consumer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiconsumer",
            index=models.Index(
                fields=["consumer_type", "-created_at"], name="api_consumer_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["consumer", "status"], name="api_key_consumer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["status", "-created_at"], name="api_key_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["-last_used_at"], name="api_key_last_used_idx"),
        ),
        migrations.AddIndex(
            model_name="apikeyscope",
            index=models.Index(
                fields=["api_key", "scope"], name="api_key_scope_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiscope",
            index=models.Index(
                fields=["is_active", "code"], name="api_scope_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(fields=["created_at"], name="api_usage_created_idx"),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(
                fields=["api_key", "-created_at"], name="api_usage_key_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(
                fields=["consumer", "-created_at"], name="api_usage_consumer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(
                fields=["endpoint", "method"], name="api_usage_endpoint_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(
                fields=["dataset_id", "-created_at"], name="api_usage_dataset_idx"
            ),
        ),
    ]
