# Generated by Django 6.0.5 on 2026-05-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_permission_remove_role_permissions_rolepermission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rolepermission",
            name="unique_role_permission",
        ),
        migrations.RemoveConstraint(
            model_name="userrole",
            name="unique_user_role",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="user",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
