# Generated by Django 6.0.5 on 2026-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0004_remove_rolepermission_unique_role_permission_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
