# Generated by Codex on 2026-07-02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TispApiResponseCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.CharField(max_length=120)),
                ("params_hash", models.CharField(max_length=64)),
                ("params", models.JSONField(default=dict)),
                ("response", models.JSONField(default=list)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "tisp_api_response_cache",
                "indexes": [
                    models.Index(fields=["endpoint", "params_hash"], name="tisp_api_re_endpoin_83ade4_idx"),
                    models.Index(fields=["fetched_at"], name="tisp_api_re_fetched_d52e2e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("endpoint", "params_hash"), name="uniq_tisp_api_response_cache_request"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TispDataValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datavaluekey", models.BigIntegerField(unique=True)),
                ("area_level", models.CharField(blank=True, max_length=20)),
                ("area_code", models.CharField(blank=True, max_length=50)),
                ("parent_code", models.CharField(blank=True, max_length=50)),
                ("area_name", models.CharField(max_length=255)),
                ("tag", models.IntegerField(default=0)),
                ("areakey", models.BigIntegerField(blank=True, null=True)),
                ("indicatorkey", models.BigIntegerField()),
                ("indicator_name", models.CharField(max_length=500)),
                ("datavalue", models.FloatField(blank=True, null=True)),
                ("time_name", models.CharField(blank=True, max_length=100)),
                ("source_name", models.CharField(blank=True, max_length=500)),
                ("source_mda", models.CharField(blank=True, max_length=255)),
                ("source_link", models.URLField(blank=True)),
                ("timeperiod_name", models.CharField(blank=True, max_length=120)),
                ("subgroupkey", models.BigIntegerField(blank=True, null=True)),
                ("timeperiodkey", models.BigIntegerField(blank=True, null=True)),
                ("subgroup_name", models.CharField(blank=True, max_length=255)),
                ("subgroup_code", models.CharField(blank=True, max_length=255)),
                ("raw", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "tisp_data_values",
                "indexes": [
                    models.Index(fields=["indicatorkey", "timeperiodkey", "subgroupkey"], name="tisp_data_v_indicat_89546a_idx"),
                    models.Index(fields=["indicator_name"], name="tisp_data_v_indicat_132cc7_idx"),
                    models.Index(fields=["area_name"], name="tisp_data_v_area_na_f592a7_idx"),
                    models.Index(fields=["time_name"], name="tisp_data_v_time_na_aac0a7_idx"),
                    models.Index(fields=["fetched_at"], name="tisp_data_v_fetched_04c24e_idx"),
                ],
            },
        ),
    ]

